# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-node:
    defaults:
      run:
        shell: bash
        working-directory: ./EXCELsior/backend
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - run: node --version
    - run: npm --version 
    - uses: actions/checkout@v3
    - run: pwd
    - run: cd  EXCELsior/backend 
    - run: ls -la 
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
