# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: backend and frotend CI

on:
  push:
    branches: [ "matan-ci" ]
  pull_request:
    branches: [ "matan-ci" ]

jobs:
  build-node:
    defaults:
      run:
        working-directory: ./EXCELsior/backend 
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - uses: actions/checkout@v3
    - run: node --version
    - run: npm --version 
    - run: pwd
    - run: ls -la 
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test | grep listening & sleep 1; pkill -f node
  build-react:
    defaults:
      run:
        working-directory: ./EXCELsior/excelsior-app
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build # currently not treating warnings as errors -- change in package.json 
    - run: npm run test